/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ist412.Views;
import ist412.Controllers.SerializedDataCntl;
import ist412.Models.Budget;
import ist412.Models.UserList;
import ist412.Models.User;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jakedotts
 */
public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form NavigationView
     */
    public NavigationView showNav;
    public NewBudgetView showNewBudget;
    ArrayList<Budget> theBudgetList = SerializedDataCntl.getSerializedDataCntl().getSerializedDataModel().getUserList().getTheUserList().get(0).getTheBudgetList();
    
    
    public DashboardView() {
        initComponents();
        Double budgetAmountLabel = theBudgetList.get(theBudgetList.size()-1).getBudgetAmount();
        BudgetItemsLabel.setText(theBudgetList.get(theBudgetList.size()-1).getBudgetName());
        BudgetAmountLabel.setText("$"+budgetAmountLabel);
        BudgetBalanceLabel.setText("$"+budgetAmountLabel);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NavButton = new javax.swing.JButton();
        BudgetItemsLabel = new javax.swing.JLabel();
        EditButton = new javax.swing.JButton();
        ViewAllButton = new javax.swing.JButton();
        NewBudgetButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BudgetBalanceLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BudgetAmountLabel = new javax.swing.JLabel();
        RefreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BUDGE-IT");

        NavButton.setText("|||");
        NavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavButtonActionPerformed(evt);
            }
        });

        BudgetItemsLabel.setText("Currently no budget items");

        EditButton.setText("EDIT");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        ViewAllButton.setText("VIEW ALL");
        ViewAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllButtonActionPerformed(evt);
            }
        });

        NewBudgetButton.setText("NEW");
        NewBudgetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBudgetButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("MONTHLY TOTALS");

        jLabel4.setText("BALANCE");

        jLabel5.setText("SPENT");

        jLabel6.setText("BUDGET");

        BudgetBalanceLabel.setText("$0.00");

        jLabel8.setText("$0.00");

        BudgetAmountLabel.setText("$0.00");

        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(BudgetItemsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(EditButton)
                        .addGap(18, 18, 18)
                        .addComponent(ViewAllButton)
                        .addGap(18, 18, 18)
                        .addComponent(NewBudgetButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel3)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BudgetBalanceLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BudgetAmountLabel))
                    .addComponent(jLabel6))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RefreshButton)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NavButton)
                    .addComponent(jLabel1)
                    .addComponent(RefreshButton))
                .addGap(47, 47, 47)
                .addComponent(BudgetItemsLabel)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewAllButton)
                    .addComponent(EditButton)
                    .addComponent(NewBudgetButton))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BudgetBalanceLabel)
                    .addComponent(jLabel8)
                    .addComponent(BudgetAmountLabel))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == NavButton){
            showNav = new NavigationView();
            showNav.setVisible(true);
            //System.out.println(NavButton.getLocationOnScreen());
        }
    }//GEN-LAST:event_NavButtonActionPerformed

    private void NewBudgetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBudgetButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == NewBudgetButton){
            showNewBudget = new NewBudgetView();
            showNewBudget.setVisible(true);
            this.setVisible(false);
            //System.out.println(NewBudgetButton.getLocationOnScreen());
        }
    }//GEN-LAST:event_NewBudgetButtonActionPerformed

    private void ViewAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == ViewAllButton){
            JOptionPane.showMessageDialog(rootPane, "You currently have no budget items to view. \n"+
                    "If you would like to add a new budget, select the add button.");
            System.out.println(ViewAllButton.getLocationOnScreen());
        }
    }//GEN-LAST:event_ViewAllButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == EditButton){
            JOptionPane.showMessageDialog(rootPane, "You currently have no budget items to edit. \n"+
                    "If you would like to add a new budget, select the add button.");
            System.out.println(EditButton.getLocationOnScreen());
        }
    }//GEN-LAST:event_EditButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == RefreshButton){
            Double budgetAmountLabel = theBudgetList.get(theBudgetList.size()-1).getBudgetAmount();
            BudgetItemsLabel.setText(theBudgetList.get(theBudgetList.size()-1).getBudgetName());
            BudgetAmountLabel.setText("$"+budgetAmountLabel);
            BudgetBalanceLabel.setText("$"+budgetAmountLabel);
        }
    }//GEN-LAST:event_RefreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardView().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BudgetAmountLabel;
    private javax.swing.JLabel BudgetBalanceLabel;
    private javax.swing.JLabel BudgetItemsLabel;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton NavButton;
    private javax.swing.JButton NewBudgetButton;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton ViewAllButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
